server:
  port: 8189
  http2:
    enabled: true

  ssl:
    key-store: C:\Program Files (x86)\ssl\keystore.jks
    key-store-password: password
    key-alias: selfsigned

jwt:
  cookie-token-key: '{"kty":"oct","k":"956PBFst1FguLr5irJD-aQ"}'

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/marketDB
    username: adm
    password: adm
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

logging:
  level:
    org.springframework.security: trace